repos:

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort
      name: isort (python)

- repo: https://github.com/google/yapf
  rev: v0.32.0
  hooks:
  - id: yapf
    args: [
      '--parallel', 
      '--in-place', 
      '--style={column_limit: 120, spaces_around_power_operator: true}'
    ]
    additional_dependencies: [toml]
